language: php

php:
  - 7.0

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs
