language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs
